[build]
  publish = "dist"  # Your build output directory
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/menu"
  to = "/menu.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

# Error page handling
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404